[package]
name = "habasi"
version = "0.1.0"
authors = ["alvazir <basha.alvazir@gmail.com>"]
edition = "2021"
rust-version = "1.69.0"
description = "Habasi - TES3 Plugin Merging Tool"
readme = "README.md"
homepage = "https://www.nexusmods.com/morrowind/mods/53002"
repository = "https://github.com/alvazir/habasi"
license = "Unlicense OR MIT"
keywords = ["cli", "tes3", "morrowind", "openmw"]
categories = ["command-line-utilities", "game development"]
publish = false

[badges]
maintenance = { status = "actively-developed" }

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
# branch = "dev"
rev = "8ea11d0e"
default-features = false
features = ["esp"]
# version = "0"

[dependencies]
clap = { version = "~4.3.0", features = ["derive", "suggestions", "wrap_help"] } # CLI
confique = { version = "~0.2.3", default-features = false, features = ["toml"] } # settings file
serde = "~1.0.163"                                                               # required by confique
anyhow = "~1.0.71"    																													 # error management
hashbrown = { version = "~0.13.2", features = ["rayon"] }                        # references

[profile.release-lto]
inherits = "release"
strip = true
lto = true
panic = "abort"
codegen-units = 1

[profile.release-lto-darwin]
inherits = "release"
# strip = true
lto = true
panic = "abort"
codegen-units = 1
