[package]
name = "habasi"
version = "0.2.6"
authors = ["alvazir <basha.alvazir@gmail.com>"]
edition = "2021"
rust-version = "1.71.1"
description = "Habasi - TES3 Plugin Merging Tool"
readme = "README.md"
homepage = "https://www.nexusmods.com/morrowind/mods/53002"
repository = "https://github.com/alvazir/habasi"
license = "Unlicense OR MIT"
keywords = ["cli", "tes3", "morrowind", "openmw"]
categories = ["command-line-utilities", "game development"]
publish = false

[badges]
maintenance = { status = "actively-developed" }

[dependencies.tes3]
# path = "../tes3"
git = "https://github.com/Greatness7/tes3"
rev = "6b6a0ff"
# branch = "dev"
default-features = false
features = ["esp"]

[dependencies]
clap = { version = "~4.3.23", features = ["derive", "suggestions", "wrap_help"] } # CLI
confique = { version = "~0.2.4", default-features = false, features = ["toml"] }  # settings file
serde = "~1.0.183"                                                                # required by confique
anyhow = "~1.0.75"    																													  # error management
hashbrown = { version = "~0.14.0", features = ["rayon"] }                         # references
dirs = "~5.0.1"                                                                   # find openmw.cfg
walkdir = "~2.3.3"                                                                # find files
rayon = "~1.7.0"                                                                  # find files in parallel
crc = "~3.0.1"                                                                    # create id for sscr with empty id

[profile.release-lto]
inherits = "release"
strip = true
lto = true
panic = "abort"
codegen-units = 1

[profile.release-lto-darwin]
inherits = "release"
# strip = true
lto = true
panic = "abort"
codegen-units = 1
